config/routes.rb
Rails.application.routes.draw do
  
  root 'users#index'
  
  resources :users 
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  before_save { self.email = email.downcase }
  
  validates :name, presence: true,
                   length: {maximum: 50}
                   
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i                 
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  validates :password, presence: true,
                       length: { minimum: 6  }
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all 
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "User successfully save."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      flash[:success] = "User update successfully."
      redirect_to @user
    else
      render "edit"
      
    end
    
  end

  def show
    @user = User.find(params[:id])
  end

  def delete
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroy successfully."
    redirect_to users_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
   def full_title(page_title = '')
     base_title = "Practice App"
     if page_title.empty?
       base_title
     else
      page_title + " | " + base_title
     end
   
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<% flash.each do |message_type, message| %>
   <div class="alert alert-<%= message_type%>"><%= message %></div>

<% end  %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any?  %>
  <div>
  <p>The form contains <%= pluralize( @user.errors.count, " error") %></p>
  
  <ul>
  <% @user.errors.full_messages.each do |msg|  %>
    <li><%= msg  %></li>
  <% end  %>
  </ul>
  </div>
<% end  %>

app/views/users/_form.html.erb
<table>
     <tr>
     <th><%= f.label :name  %></th>
     <td><%= f.text_field :name  %></td>
     </tr>
     <tr>
     <th><%= f.label :email  %></th>
     <td><%= f.email_field :email  %></td>
     </tr>
     <th><%= f.label :password  %></th>
     <td><%= f.password_field :password  %></td>
     </tr>
     <tr>
     <th><%= f.label :password_confirmation  %></th>
     <td><%= f.password_field :password_confirmation  %></td>
     </tr>  
     <tr>
     <th><%= f.label :admin  %></th>
     <td><%= f.check_box :admin  %></td>
     </tr>     
   </table> 
   

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit User")  %>
<%= link_to "Back to All Users", root_path %>

<h1>Edit User <%= @user.name %></h1>

<div>
  <%= form_for(@user) do |f|  %>
    <%= render "shared/error_messages" %>
    <%= render "form", f: f %>
    
    <div>
      <%= f.submit "Update User" %>
    </div>
   <% end  %>
</div>  

app/views/users/index.html.erb
<% provide(:title, "All users")  %>
<h1>All Users</h1>
<%= link_to "add user", new_user_path  %>
<div>
  <table>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Action</th>
    </tr>
    <% @users.each do |user|  %>
    <tr>  
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to "Edit", edit_user_path(user.id) %></td>
      <% if user.admin %>
      <td><%= link_to "Delete", user, method: :delete, data: { confirm: "Are you sure? "} %></td>
      <% end  %>
    </tr>
    <% end  %>
    
  </table>
</div>  

app/views/users/new.html.erb
<% provide(:title, "New")  %>
<%= link_to "Back to All Users", root_path  %>
<h1>Add New User</h1>
<br />
<div>
<%= form_for(@user) do |f| %>
   
   <%= render 'shared/error_messages' %>
   <%= render 'form', f: f  %>
   
   <div>
     <%= f.submit "Create User"  %>
   </div>   
<% end  %>
</div>

app/views/users/show.html.erb
<% provide(:title, "Show User")  %>
<%= link_to "Back to All Users", root_path %>

<div>
  <h1>Hi <%= @user.name %>!</h1>
  
  <table>
    <tr>
      <th>Email: </th>
      <td><%= @user.email %></td>
    </tr>  
    
  </table>    
</div>